"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sparkles, Loader2 } from "lucide-react";
import { usePresentationEditorStore } from "@/lib/store/presentation-editor-store";

export function AIPresentationGenerator() {
  const [open, setOpen] = useState(false);
  const [topic, setTopic] = useState("");
  const [tone, setTone] = useState("professional");
  const [slideCount, setSlideCount] = useState("5");
  const [isGenerating, setIsGenerating] = useState(false);
  const { addFrame, addElement, frames } = usePresentationEditorStore();

  const handleGenerate = async () => {
    setIsGenerating(true);
    
    // Simulate AI generation delay
    await new Promise(resolve => setTimeout(resolve, 2000));

    const count = parseInt(slideCount);
    const startX = frames.length > 0 
      ? Math.max(...frames.map(f => f.position.x)) + 1200 
      : 0;

    for (let i = 0; i < count; i++) {
      // Create Frame
      const frameId = addFrame({
        title: i === 0 ? topic : `Slide ${i + 1}: ${topic}`,
        position: { x: startX + (i * 1200), y: 0 },
        scale: 1,
        rotation: 0,
        width: 960,
        height: 540,
        backgroundColor: "#ffffff",
      });

      // Add Title Element
      addElement(frameId, {
        type: "text",
        content: i === 0 ? topic : `Key Point ${i}`,
        position: { x: 100, y: 100 },
        size: { width: 760, height: 100 },
        rotation: 0,
        style: {
          fontSize: i === 0 ? 72 : 48,
          fontWeight: "bold",
          fill: "#000000",
          textAlign: i === 0 ? "center" : "left"
        }
      });

      // Add Body Element
      addElement(frameId, {
        type: "text",
        content: i === 0 
          ? `A ${tone} presentation generated by AI` 
          : "• First important point\n• Second important point\n• Third important point",
        position: { x: 100, y: 250 },
        size: { width: 760, height: 200 },
        rotation: 0,
        style: {
          fontSize: 24,
          fill: "#333333",
          textAlign: i === 0 ? "center" : "left"
        }
      });
    }
    
    setIsGenerating(false);
    setOpen(false);
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="gap-2 bg-gradient-to-r from-purple-500/10 to-blue-500/10 border-purple-200 dark:border-purple-800 hover:from-purple-500/20 hover:to-blue-500/20">
          <Sparkles className="w-4 h-4 text-purple-500" />
          Create with AI
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Generate Presentation</DialogTitle>
          <DialogDescription>
            Enter a topic and let AI create a starting structure for you.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="topic">Topic</Label>
            <Input
              id="topic"
              placeholder="e.g., Church Vision 2024"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
            />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="tone">Tone</Label>
            <Select value={tone} onValueChange={setTone}>
              <SelectTrigger>
                <SelectValue placeholder="Select tone" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="professional">Professional</SelectItem>
                <SelectItem value="inspirational">Inspirational</SelectItem>
                <SelectItem value="casual">Casual</SelectItem>
                <SelectItem value="educational">Educational</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="count">Number of Slides</Label>
            <Select value={slideCount} onValueChange={setSlideCount}>
              <SelectTrigger>
                <SelectValue placeholder="Select count" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="3">3 Slides</SelectItem>
                <SelectItem value="5">5 Slides</SelectItem>
                <SelectItem value="8">8 Slides</SelectItem>
                <SelectItem value="10">10 Slides</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <DialogFooter>
          <Button onClick={handleGenerate} disabled={!topic || isGenerating}>
            {isGenerating && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Generate
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
